<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * nis is purely administrative school data, never used for login,
     * so it shouldn't be forced to hold a placeholder value. Existing
     * "TEMP-%" placeholders (generated by
     * PendaftaranPpdb::konversiJadiSiswa() before nis became optional)
     * are cleared to NULL here.
     */
    public function up(): void
    {
        Schema::table('siswa', function (Blueprint $table) {
            $table->string('nis')->nullable()->change();
        });

        DB::table('siswa')->where('nis', 'like', 'TEMP-%')->update(['nis' => null]);

        Schema::table('siswa', function (Blueprint $table) {
            $table->unique('nis');
        });
    }

    /**
     * Reverse the migrations.
     *
     * Regenerates the same "TEMP-{pendaftaran_ppdb_id}" placeholder
     * konversiJadiSiswa() used to produce, for every row this
     * migration nulled out, so the rollback is a faithful inverse.
     */
    public function down(): void
    {
        Schema::table('siswa', function (Blueprint $table) {
            $table->dropUnique(['nis']);
        });

        DB::table('siswa')->whereNull('nis')->get(['id', 'pendaftaran_ppdb_id'])->each(function ($row) {
            DB::table('siswa')->where('id', $row->id)->update(['nis' => "TEMP-{$row->pendaftaran_ppdb_id}"]);
        });

        Schema::table('siswa', function (Blueprint $table) {
            $table->string('nis')->nullable(false)->change();
        });
    }
};
